spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.url}
    username: ${db.username}
    password: ${db.password}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: ${db.ddl-auto}
    open-in-view: false
    generate-ddl: true

service:
  jwt:
    secret-key: ${jwt.secret-key}
    access-expiration: ${jwt.access-expiration}

logging:
  level:
    org:
      hibernate:
        type: trace
        binder: trace

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    groups-order: desc
    path: /api-docs.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /v1/**

# Gemini API Key
gemini:
  apikey: ${GEMINI_API_KEY}
  model: gemini-2.5-flash